export const  CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE'
export const  ADD_INPUTVAL_TO_LIST = 'ADD_INPUTVAL_TO_LIST'
export const  DELETE_ITEM_IN_LIST_INDEX = 'DELETE_ITEM_IN_LIST_INDEX'
export const  GET_LIST = 'GET_LIST'